# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/opengraph_parser/all/opengraph_parser.rbi
#
# opengraph_parser-0.2.3
class RedirectFollower
  def body; end
  def body=(arg0); end
  def headers; end
  def headers=(arg0); end
  def initialize(url, limit = nil, options = nil); end
  def redirect_limit; end
  def redirect_limit=(arg0); end
  def redirect_url; end
  def resolve; end
  def response; end
  def response=(arg0); end
  def url; end
  def url=(arg0); end
end
class RedirectFollower::TooManyRedirects < StandardError
end
class OpenGraph
  def add_image(image_url); end
  def add_metadata(metadata_container, path, content); end
  def check_images_path; end
  def description; end
  def description=(arg0); end
  def fetch_images(doc, xpath_str, attr); end
  def images; end
  def images=(arg0); end
  def initialize(src, fallback = nil, options = nil); end
  def load_fallback; end
  def metadata; end
  def metadata=(arg0); end
  def original_images; end
  def original_images=(arg0); end
  def parse_opengraph(options = nil); end
  def response; end
  def response=(arg0); end
  def src; end
  def src=(arg0); end
  def title; end
  def title=(arg0); end
  def type; end
  def type=(arg0); end
  def url; end
  def url=(arg0); end
end
