# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/titleize/all/titleize.rbi
#
# titleize-1.4.1
module Titleize
  def ends_with_punctuation?(word); end
  def phrases(title); end
  def small_word?(word); end
  def titleize(title); end
  extend Titleize
end
class String
  def titlecase!; end
  def titlecase(opts = nil); end
  def titleize!; end
  def titleize(opts = nil); end
end
